#!/bin/bash

if [[ "$1" == "--host" ]]; then
    CC=$(which cc)
    LD=$(which ld)
elif [[ "$1" == "--cross" ]]; then
    CC=$(which x86_64-elf-gcc)
    LD=$(which x86_64-elf-ld)
else
    CC=$(which x86_64-elf-gcc)
    LD=$(which x86_64-elf-ld)
    if [[ -z "$CC" || -z "$LD" ]]; then
        CC=$(which cc)
        LD=$(which ld)
    fi
fi

if [[ -z "$CC" || -z "$LD" ]]; then
    echo "Error: CC or LD not found."
    exit 1
fi

make CC="$CC" LD="$LD"
